# default rules
homepage:
  url:   /
  param: { module: admin, action: index }

login:
  url:   /login
  param: { module: admin, action: login }
  
logout:
  url:   /logout
  param: { module: admin, action: logout }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
