default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [sf_admin/main,sf_admin/theme]

  javascripts:    [prototype,sf_admin/JSCookMenu_mini,sf_admin/theme]

  has_layout:     on
  layout:         layout
