rendering: ~
security: 
  class: jtBasicSecurityFilter
remember: 
  class: jtBasicFilter

timezone:
  class: TimezoneFilter
  
soap_parameter:
  class: ckSoapParameterFilter
  param:
    condition: %APP_ENABLE_SOAP_PARAMETER%

cache:     ~
common:    ~
execution: ~
