default:
  http_metas:
    content-type: text/html

  metas:
    title:        JoTAG
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [jotag/reset,i18n/style]

  javascripts:    [prototype,overlabel,bookmark,importer]

  has_layout:     on
  layout:         layout
