generator:
  class:              sfAdvancedAdminGenerator
  param:
    model_class:      Badge
    theme:            default
    css:              sf_admin/main

    list:
      title:          Badge manager 
      display:        [=name,template,_is_active,_is_default]
      fields:
        is_active:       { name: Status }
        is_default:      { name: Default }
      max_per_page:      10
      actions:
        _create:         { name: New }
      object_actions:
        edit:        { action: edit, icon: %sf_admin_web_dir%/images/edit_icon.png, name: Edit this badge, params: title='Edit this badge' }
        delete:      { action: delete, icon: %sf_admin_web_dir%/images/delete_icon.png, name: Delete this badge, params: title='Delete this badge' confirm='Are you sure you wish to delete this badge?' }

    create:
      title:          Badge manager: new
      display:        
        "Details":        [id,name,template,thumbnail,is_active]
      fields:
        is_active:        { name: Status }
        name:             { params: size=40 }
      actions:
        _list:            { name: Close }
        _save_and_list:   { name: Save }

    edit:
      title:          Language manager: edit badge %%name%%
      display:        
        "Details":        [id,name,template,thumbnail,is_active]
      fields:
        is_active:        { name: Status }
        name:             { params: size=40 }
      actions:
        _delete:          { name: Delete }
        _list:            { name: Close }
        _save_and_list:   { name: Save }